SRC_CPPS = \
		   src/logger/Logger.cpp \
		   src/device/Device.cpp \
		   src/device/DualDevice.cpp \
		   src/stream/Stream.cpp \
		   src/acquire/Acquire.cpp \
		   src/device/ParamManager.cpp \
		   src/camera/Camera.cpp \


EXEC_SRC = \
			PvStreamSample.cpp \
			CameraNodeSample.cpp \

SRC_HS	 = \
			-Isrc/logger \
		   -Isrc/device \
		   -Isrc/stream \
		   -Isrc/acquire \
		   -Isrc/camera \
		   



include ./.Makefile
