SRC_CPPS = \
           PvStreamSample.cpp \
		    src/logger/Logger.cpp \
		   src/device/Device.cpp \
		   src/device/DualDevice.cpp \
		   src/stream/Stream.cpp \
		   src/acquire/Acquire.cpp \
		   src/device/ParamManager.cpp \
		  

SRC_HS	 = \
			-Isrc/logger \
		   -Isrc/device \
		   -Isrc/stream \
		   -Isrc/acquire \
		   

EXEC     = PvStreamSample



include ./.Makefile
