FROM ros:humble-ros-base-jammy

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apt update && apt install -y sudo \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd -g ${GROUP_ID} appgroup && \
    useradd -m -u ${USER_ID} -g appgroup appuser \
    && echo "appuser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/appuser




# 작업 디렉토리 설정
WORKDIR /app



# Turtlebot Navigation 설치


RUN apt clean && apt update

RUN apt upgrade -y
RUN apt install -y ros-humble-turtlebot4-description
RUN apt install -y ros-humble-turtlebot4-msgs
RUN apt install -y ros-humble-turtlebot4-navigation
RUN apt install -y ros-humble-turtlebot4-node
RUN apt install -y ros-humble-theora-image-transport
RUN apt-get install -y iputils-ping iproute2

# pip 설치
RUN apt install -y python3-pip




# Python 패키지 설치
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Flask 애플리케이션 코드 및 기타 필요한 파일 복사
COPY . .
RUN find / -type d -name "instance" -exec rm -rf {} +

SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

# /etc/turtlebot4_discovery/ 디렉터리 생성
RUN mkdir -p /etc/turtlebot4_discovery/

# 사용자 변경
USER appuser

RUN source /opt/ros/humble/setup.bash



CMD ["python3", "app.py"]