version: '3.7'
services:
  slam_app:
    build: ./slam
    privileged: true
    environment:
      - ROS_DISCOVERY_SERVER=192.168.185.3:11811
      - ROS_DOMAIN_ID=0
      - FASTRTPS_LOG_LEVEL=Info
      - UID=1000
      - GID=1000
    network_mode: "host"
    ipc: host
    pid: host

  # rosout_app:
  #   build: ./logger
  #   privileged: true
  #   environment:
  #     - ROS_DISCOVERY_SERVER=192.168.185.3:11811
  #     - ROS_DOMAIN_ID=0
  #     - FASTRTPS_LOG_LEVEL=Info
  #     - UID=1000
  #     - GID=1000
  #   network_mode: "host"
  #   ipc: host
  #   pid: host


networks:
  slam_node_network:
    driver: macvlan
    driver_opts:
      parent: docker0  # eth0을 예시로 사용; 실제 네트워크 인터페이스에 맞춰서 변경해야 합니다.
    ipam:
      config:
        - subnet: 192.168.180.0/24
